require('dotenv').config();
const express=require('express');
const cors=require('cors');
const path=require('path');
const multer=require('multer');
const connectDB=require('./config/db');
const authRoutes=require('./Authentication/authRoutes');
const profileRoutes=require('./Profiles/profileRoutes');
const jobRoutes=require('./Jobs/jobRoutes');
const applicationRoutes=require('./Applications/applicationRoutes');
const app=express();
app.use(cors({origin:'http://localhost:5173'}));
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use('/uploads',express.static(path.join(__dirname,'uploads')));
app.use('/api/auth',authRoutes);
app.use('/api/profile',profileRoutes);
app.use('/api/jobs',jobRoutes);
app.use('/api/applications',applicationRoutes);
app.get('/',(req,res)=>res.json({name:'HireFlow API',status:'running'}));
app.use((error,req,res,next)=>{ if(error instanceof multer.MulterError) return res.status(400).json({message:error.message}); if(error) return res.status(400).json({message:error.message}); next(); });
connectDB();
const port=process.env.PORT||3000;
app.listen(port,()=>console.log(`HireFlow API listening on port ${port}`));
